image: ondrejsika/ci

stages:
    - deploy dev
    - deploy prod

.deploy: &deploy
    script:
        - helm repo add ondrejsika https://helm.oxs.cz
        - helm upgrade --install dev ondrejsika/one-image
            --set host=$CI_PROJECT_PATH_SLUG.$KUBE_INGRESS_BASE_DOMAIN

deploy dev:
    <<: *deploy
    stage: deploy dev
    environment:
        name: dev
        url: https://$CI_PROJECT_PATH_SLUG.$KUBE_INGRESS_BASE_DOMAIN

deploy prod:
    <<: *deploy
    stage: deploy prod
    environment:
        name: prod
        url: https://$CI_PROJECT_PATH_SLUG.$KUBE_INGRESS_BASE_DOMAIN
